"""Enums added  migration

Revision ID: 7f93f4d85c1b
Revises: 11f88e7b5eaf
Create Date: 2025-02-12 14:08:20.277569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7f93f4d85c1b'
down_revision: Union[str, None] = '11f88e7b5eaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'document_type',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('NOT_VERIFIED', 'VERIFIED', 'PENDING', name='documentstatus'),
               existing_nullable=True)
    op.alter_column('documents', 'is_verified',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Enum('NOT_VERIFIED', 'VERIFIED', 'PENDING', name='documentstatus'),
               existing_nullable=True)
    op.alter_column('users', 'is_document_verified',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Enum('NOT_VERIFIED', 'VERIFIED', 'PENDING', name='documentstatus'),
               existing_nullable=True)
    op.alter_column('users', 'otp_sent',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Enum('SENT', 'VERIFIED', 'EXPIRED', name='otpstatus'),
               existing_nullable=True)
    op.alter_column('users', 'otp_verified',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Enum('SENT', 'VERIFIED', 'EXPIRED', name='otpstatus'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'otp_verified',
               existing_type=sa.Enum('SENT', 'VERIFIED', 'EXPIRED', name='otpstatus'),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('users', 'otp_sent',
               existing_type=sa.Enum('SENT', 'VERIFIED', 'EXPIRED', name='otpstatus'),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('users', 'is_document_verified',
               existing_type=sa.Enum('NOT_VERIFIED', 'VERIFIED', 'PENDING', name='documentstatus'),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('documents', 'is_verified',
               existing_type=sa.Enum('NOT_VERIFIED', 'VERIFIED', 'PENDING', name='documentstatus'),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('documents', 'document_type',
               existing_type=sa.Enum('NOT_VERIFIED', 'VERIFIED', 'PENDING', name='documentstatus'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###
