"""change field name fullname to full_name

Revision ID: 11ca2c73a045
Revises: a6fbb8b1e92a
Create Date: 2025-02-21 10:43:09.534393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '11ca2c73a045'
down_revision: Union[str, None] = 'a6fbb8b1e92a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.String(length=100), nullable=False))
    op.drop_column('users', 'fullname')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fullname', mysql.VARCHAR(length=100), nullable=False))
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
