"""Update document related field

Revision ID: 5732e5897e36
Revises: 7db40dd768be
Create Date: 2025-02-14 15:11:11.190505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils as su
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5732e5897e36'
down_revision: Union[str, None] = '7db40dd768be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'document_type',
               existing_type=mysql.ENUM('AADHAAR', 'PAN', 'PASSPORT', 'ELECTION'),
               nullable=False)
    op.alter_column('documents', 'document_image_path',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_column('documents', 'is_verified')
    op.alter_column('users', 'aadhaar_verified',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Enum('NOT_VERIFIED', 'VERIFIED', 'PENDING', 'REJECTED', name='verificationstatus'),
               existing_nullable=True)
    op.alter_column('users', 'pan_verified',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Enum('NOT_VERIFIED', 'VERIFIED', 'PENDING', 'REJECTED', name='verificationstatus'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'pan_verified',
               existing_type=sa.Enum('NOT_VERIFIED', 'VERIFIED', 'PENDING', 'REJECTED', name='verificationstatus'),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('users', 'aadhaar_verified',
               existing_type=sa.Enum('NOT_VERIFIED', 'VERIFIED', 'PENDING', 'REJECTED', name='verificationstatus'),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.add_column('documents', sa.Column('is_verified', mysql.ENUM('NOT_VERIFIED', 'VERIFIED', 'PENDING'), nullable=True))
    op.alter_column('documents', 'document_image_path',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('documents', 'document_type',
               existing_type=mysql.ENUM('AADHAAR', 'PAN', 'PASSPORT', 'ELECTION'),
               nullable=True)
    # ### end Alembic commands ###
