"""change expiry in otp_model for aware utc

Revision ID: 6cf4ba1e1266
Revises: 11ca2c73a045
Create Date: 2025-02-24 11:47:32.805121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cf4ba1e1266'
down_revision: Union[str, None] = '11ca2c73a045'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
