"""Eums added for document verification

Revision ID: 7db40dd768be
Revises: d95e8c547be9
Create Date: 2025-02-14 14:55:15.931369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils as su


# revision identifiers, used by Alembic.
revision: str = '7db40dd768be'
down_revision: Union[str, None] = 'd95e8c547be9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('unique_otp_expiry', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('unique_otp_expiry', 'users', ['otp', 'otp_expiry'], unique=True)
    # ### end Alembic commands ###
