"""Removed is_document_verified from User model finally

Revision ID: 84b8325e169a
Revises: bb6c50e8a89e
Create Date: 2025-02-14 15:17:38.685236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils as su
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '84b8325e169a'
down_revision: Union[str, None] = 'bb6c50e8a89e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_document_verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_document_verified', mysql.ENUM('NOT_VERIFIED', 'VERIFIED', 'PENDING'), nullable=True))
    # ### end Alembic commands ###
