"""Add email and phone verification fields to User

Revision ID: a6fbb8b1e92a
Revises: 37ac2ea90897
Create Date: 2025-02-20 17:05:24.033776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a6fbb8b1e92a'
down_revision: Union[str, None] = '37ac2ea90897'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_email_verified', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_phone_verified', sa.Boolean(), nullable=False))
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', mysql.VARCHAR(length=50), nullable=False))
    op.drop_column('users', 'is_phone_verified')
    op.drop_column('users', 'is_email_verified')
    # ### end Alembic commands ###
