"""Removed is_document_verified from User model

Revision ID: bb6c50e8a89e
Revises: 5732e5897e36
Create Date: 2025-02-14 15:15:21.588555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils as su


# revision identifiers, used by Alembic.
revision: str = 'bb6c50e8a89e'
down_revision: Union[str, None] = '5732e5897e36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
